export const pregnancyFormData = {
  age: '',
  abortion: '',
  barangay: '',
  barangay_center_id: '',
  barangay_health_station: '',
  birth_date: '',
  birth_place: '',
  bemoc: 'St. Paul Hospital',
  bemoc_address: 'Poblacion Tagoloan',
  cemoc: 'St. Paul Hospital',
  cemoc_address: 'Poblacion Tagoloan',
  contact: '',
  contact_person_name: '',
  contact_person_number: '',
  contact_person_relationship: '',
  edc: '',
  firstname: '',
  gravidity: '',
  lastname: '',
  lmp: '',
  middlename: '',
  midwife_id: '',
  municipality: 1248,
  parity: '',
  patient_id: '',
  patient_type: '',
  province: 57,
  region: 13,
  religion: 'Roman Catholic',
  referral_unit: 'St. Paul Hospital',
  sex: 'female',
  status: 'single',
  zone: '',
  barangay_name: '',
  nurse_name: '',
  nurse_id: '',
  midwife_name: '',
  municipality_name: '',
  province_name: '',
  region_name: '',
  date_delivery: '',
  anc_given: '',
  outcome_sex: '',
  outcome_weight: '',
  place_of_delivery: '',
  attended_by: '',
  risk_codes: [{ risk_code: '', date_detected: '', risk_status: '' }],
};

export const pregnancyEditFormData = (data = {}) => ({
  age: '',
  abortion: '',
  barangay: '',
  barangay_center_id: '',
  barangay_health_station: '',
  birth_date: '',
  birth_place: '',
  bemoc: '',
  bemoc_address: '',
  cemoc: '',
  cemoc_address: '',
  contact: '',
  contact_person_name: '',
  contact_person_number: '',
  contact_person_relationship: '',
  edc: '',
  firstname: '',
  gravidity: '',
  lastname: '',
  lmp: '',
  middlename: '',
  midwife_id: '',
  municipality: '',
  parity: '',
  patient_id: '',
  patient_type: 'edit',
  province: '',
  region: '',
  religion: '',
  referral_unit: '',
  sex: '',
  status: '',
  zone: '',
  barangay_name: '',
  nurse_name: '',
  nurse_id: '',
  midwife_name: '',
  municipality_name: '',
  province_name: '',
  region_name: '',
  date_delivery: '',
  anc_given: '',
  outcome_sex: '',
  outcome_weight: '',
  place_of_delivery: '',
  attended_by: '',
  risk_codes: [{ risk_code: '', date_detected: '', risk_status: '' }],
  ...data,
});

export const prenatalVisitFormData = {
  pregnancy_tracking_id: '',
  date: new Date().toLocaleDateString('en-CA'),
  weight: '',
  bp: '',
  temp: '',
  rr: '',
  pr: '',
  two_sat: '',
  fht: '',
  fh: '',
  aog: '',
  term: '',
  preterm: '',
  post_term: '',
  living_children: '',
};

export const prenatalVisitEditFormData = (data = {}) => ({
  pregnancy_tracking_id: '',
  date: '',
  weight: '',
  bp: '',
  temp: '',
  rr: '',
  pr: '',
  two_sat: '',
  fht: '',
  fh: '',
  aog: '',
  term: '',
  preterm: '',
  post_term: '',
  living_children: '',
  ...data,
});

export const outPatientFormData = {
  pregnancy_tracking_id: '',
  date: new Date().toLocaleDateString('en-CA'),
  time: new Date().toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  }),
  height: '',
  weight: '',
  bp: '',
  temp: '',
  rr: '',
  pr: '',
  two_sat: '',
};

export const outPatientEditFormData = (data = {}) => ({
  pregnancy_tracking_id: '',
  date: '',
  time: '',
  height: '',
  weight: '',
  bp: '',
  temp: '',
  rr: '',
  pr: '',
  two_sat: '',
  ...data,
});

export const immunizationFormData = {
  pregnancy_tracking_id: '',
  tetanus_first_given: '',
  tetanus_second_given: '',
  tetanus_third_given: '',
  tetanus_fourth_given: '',
  tetanus_fifth_given: '',
  tetanus_first_comeback: '',
  tetanus_second_comeback: '',
  tetanus_third_comeback: '',
  tetanus_fourth_comeback: '',
  tetanus_fifth_comeback: '',
  covid_first_given: '',
  covid_second_given: '',
  covid_booster_given: '',
  covid_first_comeback: '',
  covid_second_comeback: '',
  covid_booster_comeback: '',
  other_vaccine_name: '',
  other_first_given: '',
  other_second_given: '',
  other_third_given: '',
  other_fourth_given: '',
  other_fifth_given: '',
  other_first_comeback: '',
  other_second_comeback: '',
  other_third_comeback: '',
  other_fourth_comeback: '',
  other_fifth_comeback: '',
};

export const immunizationEditFormData = (data = {}) => ({
  pregnancy_tracking_id: '',
  tetanus_first_given: '',
  tetanus_second_given: '',
  tetanus_third_given: '',
  tetanus_fourth_given: '',
  tetanus_fifth_given: '',
  tetanus_first_comeback: '',
  tetanus_second_comeback: '',
  tetanus_third_comeback: '',
  tetanus_fourth_comeback: '',
  tetanus_fifth_comeback: '',
  covid_first_given: '',
  covid_second_given: '',
  covid_booster_given: '',
  covid_first_comeback: '',
  covid_second_comeback: '',
  covid_booster_comeback: '',
  other_vaccine_name: '',
  other_first_given: '',
  other_second_given: '',
  other_third_given: '',
  other_fourth_given: '',
  other_fifth_given: '',
  other_first_comeback: '',
  other_second_comeback: '',
  other_third_comeback: '',
  other_fourth_comeback: '',
  other_fifth_comeback: '',
  ...data,
});
