export const pregnancyFormData = {
  age: '',
  abortion: '',
  barangay: '',
  barangay_center_id: '',
  barangay_health_station: '',
  birth_date: '',
  birth_place: '',
  bemoc: 'St. Paul Hospital',
  bemoc_address: 'Poblacion Tagoloan',
  cmoc: 'St. Paul Hospital',
  cmoc_address: 'Poblacion Tagoloan',
  contact: '',
  contact_person_name: '',
  contact_person_number: '',
  contact_person_relationship: '',
  edc: '',
  firstname: '',
  gravidity: '',
  lastname: '',
  lmp: '',
  middlename: '',
  midwife_id: '',
  municipality: '',
  parity: '',
  patient_id: '',
  patient_type: '',
  province: '',
  region: '',
  religion: '',
  referral_unit: 'St. Paul Hospital',
  sex: 'female',
  status: '',
  zone: '',
  barangay_name: '',
  nurse_name: '',
  nurse_id: '',
  midwife_name: '',
  municipality_name: '',
  province_name: '',
  region_name: '',
  date_delivery: '',
  anc_given: '',
  outcome_sex: '',
  outcome_weight: '',
  place_of_delivery: '',
  attended_by: '',
  phic: '',
};

export const pregnancyEditFormData = (data = {}) => ({
  age: '',
  abortion: '',
  barangay: '',
  barangay_center_id: '',
  barangay_health_station: '',
  birth_date: '',
  birth_place: '',
  bemoc: 'St. Paul Hospital',
  bemoc_address: 'Poblacion Tagoloan',
  cmoc: 'St. Paul Hospital',
  cmoc_address: 'Poblacion Tagoloan',
  contact: '',
  contact_person_name: '',
  contact_person_number: '',
  contact_person_relationship: '',
  edc: '',
  firstname: '',
  gravidity: '',
  lastname: '',
  lmp: '',
  middlename: '',
  midwife_id: '',
  municipality: '',
  parity: '',
  patient_id: '',
  patient_type: '',
  province: '',
  region: '',
  religion: '',
  referral_unit: 'St. Paul Hospital',
  sex: 'female',
  status: '',
  zone: '',
  barangay_name: '',
  nurse_name: '',
  nurse_id: '',
  midwife_name: '',
  municipality_name: '',
  province_name: '',
  region_name: '',
  date_delivery: '',
  anc_given: '',
  outcome_sex: '',
  outcome_weight: '',
  place_of_delivery: '',
  attended_by: '',
  phic: '',
  ...data,
});
